.TH "BPMap" 3 "12 Nov 2009" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BPMap \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bptypes.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.ti -1c
.RI "struct \fBBPMapElem_t\fP * \fBelements\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a structure representing a map 
.SH "Field Documentation"
.PP 
.SS "struct \fBBPMapElem_t\fP* \fBBPMap::elements\fP\fC [read]\fP"An array of BPMapElem structures containing keys and values 
.SS "unsigned int \fBBPMap::size\fP"The number of elements in the list 

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
