.TH "BPMapElem_t" 3 "12 Nov 2009" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BPMapElem_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bptypes.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBPString\fP \fBkey\fP"
.br
.ti -1c
.RI "\fBBPElement\fP * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A BPMapElem contains a pointer to a UTF8 string, and a pointer to a BPElement structure containing the value 
.SH "Field Documentation"
.PP 
.SS "\fBBPString\fP \fBBPMapElem_t::key\fP"
.SS "\fBBPElement\fP* \fBBPMapElem_t::value\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
